/** AUTO-GERADO por scripts/extract-lsp-functions.mjs — não editar à mão. */
import type { LspFunctionEntry } from "./function-catalog.types";

export const LSP_FUNCTION_CATALOG_GENERATED: LspFunctionEntry[] = [
  {
    label: "AbrirCursor",
    insertText: "AbrirCursor($0);",
    detail: "AbrirCursor",
    documentation: "**AbrirCursor**\n\n_Fonte: referencia-rapida.md_",
    isSnippet: true,
  },
  {
    label: "AdicionaDadosGrade",
    insertText: "AdicionaDadosGrade(${1:ControlName}, ${2:Linha}, ${3:Coluna}, ${4:Texto});",
    detail: "AdicionaDadosGrade(Alfa ControlName, Numero Linha, Numero Coluna, Alfa Texto);",
    documentation: "**AdicionaDadosGrade**\n`AdicionaDadosGrade(Alfa ControlName, Numero Linha, Numero Coluna, Alfa Texto);`\n\nAdiciona ou define texto em uma célula específica de um controle tipo grade.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "AlfaParaData",
    insertText: "AlfaParaData(${1:texto}, ${2:p2});",
    detail: "AlfaParaData(<texto>, <data>);",
    documentation: "**AlfaParaData**\n`AlfaParaData(<texto>, <data>);`\n\nConverte um valor alfanumérico para o tipo Data.\n\n\n_Fonte: cast-de-variavel.md_",
    isSnippet: true,
  },
  {
    label: "AlfaParaDecimal",
    insertText: "AlfaParaDecimal(${1:texto}, ${2:decimal});",
    detail: "AlfaParaDecimal(<texto>, <decimal>);",
    documentation: "**AlfaParaDecimal**\n`AlfaParaDecimal(<texto>, <decimal>);`\n\nConverte um valor alfanumérico para o tipo Decimal.\n\n\n_Fonte: cast-de-variavel.md_",
    isSnippet: true,
  },
  {
    label: "AlfaParaInt",
    insertText: "AlfaParaInt(${1:texto}, ${2:inteiro});",
    detail: "AlfaParaInt(<texto>, <inteiro>);",
    documentation: "**AlfaParaInt**\n`AlfaParaInt(<texto>, <inteiro>);`\n\nConverte um valor alfanumérico para o tipo Inteiro.\n\n\n_Fonte: cast-de-variavel.md_",
    isSnippet: true,
  },
  {
    label: "AlteraControle",
    insertText: "AlteraControle(${1:NomedoControle}, ${2:Propriedade}, ${3:Parametro});",
    detail: "AlteraControle(\"Nome do Controle\", \"Propriedade\", \"Parametro\");",
    documentation: "**AlteraControle**\n`AlteraControle(\"Nome do Controle\", \"Propriedade\", \"Parametro\");`\n\nPermite alterar o conteúdo de algumas propriedades dos controles.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "AlteraValorFormula",
    insertText: "AlteraValorFormula(${1:NomeFormula}, ${2:Valor});",
    detail: "AlteraValorFormula(Alfa NomeFormula, Numero Valor);",
    documentation: "**AlteraValorFormula**\n`AlteraValorFormula(Alfa NomeFormula, Numero Valor);`\n\nAltera o valor de um controle fórmula pelo seu nome.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "AnoBissexto",
    insertText: "AnoBissexto(${1:p1}, ${2:bissexto});",
    detail: "AnoBissexto(<data>, <bissexto>);",
    documentation: "**AnoBissexto**\n`AnoBissexto(<data>, <bissexto>);`\n\nEsta função tem por objetivo retornar a informação se um ano é ou não bissexto tomando como base o ano da data passada.\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "ArqExiste",
    insertText: "ArqExiste(${1:caminhoArquivo});",
    detail: "vnRet = ArqExiste(<caminhoArquivo>);",
    documentation: "**ArqExiste**\n`vnRet = ArqExiste(<caminhoArquivo>);`\n\nVerifica se um arquivo físico existe no local especificado.\n\n\n_Fonte: validacao-e-verificacao.md_",
    isSnippet: true,
  },
  {
    label: "Arredonda",
    insertText: "Arredonda(${1:valor}, ${2:decimais});",
    detail: "Arredonda(<valor>, <decimais>);",
    documentation: "**Arredonda**\n`Arredonda(<valor>, <decimais>);`\n\nEsta função arredonda um valor, conforme a precisão informada.\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "ArredondaABNT",
    insertText: "ArredondaABNT(${1:valor}, ${2:decimais});",
    detail: "ArredondaABNT(<valor>, <decimais>);",
    documentation: "**ArredondaABNT**\n`ArredondaABNT(<valor>, <decimais>);`\n\nEsta função aplica a regra de arredondamento da ABNT, conforme a precisão informada.\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "ArredondarValor",
    insertText: "ArredondarValor(${1:valorVariavel}, ${2:precisao});",
    detail: "ArredondarValor(<valorVariavel>, <precisao>);",
    documentation: "**ArredondarValor**\n`ArredondarValor(<valorVariavel>, <precisao>);`\n\nEsta função arredonda determinado valor, conforme a precisão informada.\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "ArredondaValorTipoAcerto",
    insertText: "ArredondaValorTipoAcerto($0);",
    detail: "Arredonda um valor tipo acerto, conforme a precisão informada.",
    documentation: "**ArredondaValorTipoAcerto**\n\nArredonda um valor tipo acerto, conforme a precisão informada.\n\n_Fonte: funcoes-gerais.md_",
    isSnippet: true,
  },
  {
    label: "AtivaLimpezaParamEnt",
    insertText: "AtivaLimpezaParamEnt();",
    detail: "nomePorta.AtivaLimpezaParamEnt();",
    documentation: "**AtivaLimpezaParamEnt**\n`nomePorta.AtivaLimpezaParamEnt();`\n\nFunção que habilita a Limpeza Automática dos Parâmetros de Entrada após a Execução, ou seja, após qualquer execução da porta (função `Executar()`), todos os parâmetros de entrada serão limpos sendo necessário alimentá-los novamente para uma nova execução. Caso esta função não seja chamada dentro da Regra LSP, a porta vai assumir a Limpeza Automática como habilitada por padrão.\n\n\n_Fonte: web-service.md_",
  },
  {
    label: "AtualizaBarraProgresso",
    insertText: "AtualizaBarraProgresso(${1:percentual}, ${2:mensagem});",
    detail: "AtualizaBarraProgresso(<percentual>, <mensagem>);",
    documentation: "**AtualizaBarraProgresso**\n`AtualizaBarraProgresso(<percentual>, <mensagem>);`\n\nAtualiza o progresso e a mensagem da barra.\n\n\n_Fonte: interface-e-feedback-do-usuario.md_",
    isSnippet: true,
  },
  {
    label: "Base64Decode",
    insertText: "Base64Decode(${1:textoBase64}, ${2:textoOriginal});",
    detail: "Base64Decode(<textoBase64>, <textoOriginal>);",
    documentation: "**Base64Decode**\n`Base64Decode(<textoBase64>, <textoOriginal>);`\n\nDecodifica uma string Base64.\n\n\n_Fonte: criptografia-e-seguranca.md_",
    isSnippet: true,
  },
  {
    label: "Base64Encode",
    insertText: "Base64Encode(${1:textoOriginal}, ${2:textoBase64});",
    detail: "Base64Encode(<textoOriginal>, <textoBase64>);",
    documentation: "**Base64Encode**\n`Base64Encode(<textoOriginal>, <textoBase64>);`\n\nCodifica uma string em Base64.\n\n\n_Fonte: criptografia-e-seguranca.md_",
    isSnippet: true,
  },
  {
    label: "CalculaAlfa",
    insertText: "CalculaAlfa(${1:operacao}, ${2:argumento1}, ${3:argumento2}, ${4:resultado});",
    detail: "CalculaAlfa(<operacao>, <argumento1>, <argumento2>, <resultado>);",
    documentation: "**CalculaAlfa**\n`CalculaAlfa(<operacao>, <argumento1>, <argumento2>, <resultado>);`\n\nRealiza operações matemáticas com valores alfanuméricos.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "Cancel",
    insertText: "Cancel(${1|1,2,3|});",
    detail: "Cancel(1|2|3)",
    documentation: "**Cancel(n)** — ver docs/lsp/cancel.md",
    isSnippet: true,
  },
  {
    label: "CancelarRelatorio",
    insertText: "CancelarRelatorio();",
    detail: "CancelarRelatorio();",
    documentation: "**CancelarRelatorio**\n`CancelarRelatorio();`\n\nCancela o relatório que está sendo executado.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
  },
  {
    label: "CaracterParaAlfa",
    insertText: "CaracterParaAlfa(${1:caractere}, ${2:destino});",
    detail: "CaracterParaAlfa(<caractere>, <destino>);",
    documentation: "**CaracterParaAlfa**\n`CaracterParaAlfa(<caractere>, <destino>);`\n\nConverte um caracter (que fica armazenado pelo código ASCII) para o valor Alfanumérico correspondente.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "CarregaImagemControle",
    insertText: "CarregaImagemControle(${1:NomeDoControle}, ${2:ArquivoOuBanco}, ${3:CaminhoOuCampo}, ${4:SQL});",
    detail: "CarregaImagemControle(Alfa NomeDoControle, Numero ArquivoOuBanco, Alfa CaminhoOuCampo, Alfa SQL);",
    documentation: "**CarregaImagemControle**\n`CarregaImagemControle(Alfa NomeDoControle, Numero ArquivoOuBanco, Alfa CaminhoOuCampo, Alfa SQL);`\n\nCarrega uma imagem do tipo .BMP ou .JPG a partir de um arquivo ou banco de dados.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "CarregaImgControle",
    insertText: "CarregaImgControle(${1:NomeDoControleImagem}, ${2:Arquivo0Banco1Variavel2}, ${3:CaminhoCampoNome}, ${4:SQL}, ${5:SqlSenior2});",
    detail: "Carrega uma imagem do banco, arquivo ou variável para um controle imagem do modelo.",
    documentation: "**CarregaImgControle**\n`CarregaImgControle(Alfa NomeDoControleImagem, Numero Arquivo0Banco1Variavel2, Alfa CaminhoCampoNome, Alfa SQL, Numero SqlSenior2);`\n\nCarrega uma imagem do banco, arquivo ou variável para um controle imagem do modelo.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "CarregaImgVetorialControle",
    insertText: "CarregaImgVetorialControle(${1:NomeDoControleImagem}, ${2:Caminho}, ${3:Xms}, ${4:Xmx});",
    detail: "CarregaImgVetorialControle(Alfa NomeDoControleImagem, Alfa Caminho, Numero Xms, Numero Xmx);",
    documentation: "**CarregaImgVetorialControle**\n`CarregaImgVetorialControle(Alfa NomeDoControleImagem, Alfa Caminho, Numero Xms, Numero Xmx);`\n\nCarrega uma imagem DXF a partir de um arquivo para o controle Imagem e ImagemVetorial do modelo.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "CarregarTextoArq",
    insertText: "CarregarTextoArq(${1:arquivo}, ${2:texto});",
    detail: "CarregarTextoArq(<arquivo>, <texto>);",
    documentation: "**CarregarTextoArq**\n`CarregarTextoArq(<arquivo>, <texto>);`\n\nEsta função carrega para uma variável alfanumérica o conteúdo de um arquivo texto.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "CodData",
    insertText: "CodData(${1:dia}, ${2:mes}, ${3:ano});",
    detail: "vdData = CodData(<dia>, <mes>, <ano>);",
    documentation: "**CodData**\n`vdData = CodData(<dia>, <mes>, <ano>);`\n\nPossibilita a composição de uma data, montando-a através de dia, mês e ano. Retorna a data (usar em atribuição).\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "CodigoEspNivel",
    insertText: "CodigoEspNivel(${1:Nivel}, ${2:CodigoNivel});",
    detail: "CodigoEspNivel(Numero Nivel, Alfa End CodigoNivel);",
    documentation: "**CodigoEspNivel**\n`CodigoEspNivel(Numero Nivel, Alfa End CodigoNivel);`\n\nRetorna o código especial de acordo com um determinado nível.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "Concatena",
    insertText: "Concatena(${1:str1}, ${2:str2}, ${3:str3}, ${4:destino});",
    detail: "Concatena(<str1>, <str2>, <str3>, <destino>);",
    documentation: "**Concatena**\n`Concatena(<str1>, <str2>, <str3>, <destino>);`\n\nEsta função concatena até 3 campo/variáveis tipo alfa, formando uma só variável.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "ConfiguraPontoGrafico",
    insertText: "ConfiguraPontoGrafico(${1:ControlName}, ${2:Caractere}, ${3:TipoPonto}, ${4:IndiceFigura}, ${5:Interrompido});",
    detail: "Configura pontos em gráficos de figuras variáveis (linhas) antes de adicionar valores.",
    documentation: "**ConfiguraPontoGrafico**\n`ConfiguraPontoGrafico(Alfa ControlName, Alfa Caractere, Numero TipoPonto, Numero IndiceFigura, Numero Interrompido);`\n\nConfigura pontos em gráficos de figuras variáveis (linhas) antes de adicionar valores.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "ConverteCodificacaoString",
    insertText: "ConverteCodificacaoString(${1:textoOrigem}, ${2:codificacao}, ${3:textoDestino});",
    detail: "vnRetorno = ConverteCodificacaoString(<textoOrigem>, <codificacao>, <textoDestino>);",
    documentation: "**ConverteCodificacaoString**\n`vnRetorno = ConverteCodificacaoString(<textoOrigem>, <codificacao>, <textoDestino>);`\n\nEsta função altera a codificação de um texto contido em uma variável, onde este texto com a codificação alterada pode ser utilizado para comunicação com web services.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "ConverteDataBanco",
    insertText: "ConverteDataBanco(${1:datNum}, ${2:datAlf});",
    detail: "ConverteDataBanco(<datNum>, <datAlf>);",
    documentation: "**ConverteDataBanco**\n`ConverteDataBanco(<datNum>, <datAlf>);`\n\nConverter uma data qualquer, para o formato de data do banco de dados.\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "ConverteDataSqlSenior2",
    insertText: "ConverteDataSqlSenior2(${1:datNum}, ${2:datSql});",
    detail: "ConverteDataSqlSenior2(<datNum>, <datSql>);",
    documentation: "**ConverteDataSqlSenior2**\n`ConverteDataSqlSenior2(<datNum>, <datSql>);`\n\nConverter datas para o formato SQL Senior 2.\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "ConverteDataToDB",
    insertText: "ConverteDataToDB(${1:datNum}, ${2:datAlf});",
    detail: "ConverteDataToDB(<datNum>, <datAlf>);",
    documentation: "**ConverteDataToDB**\n`ConverteDataToDB(<datNum>, <datAlf>);`\n\nConverter uma data qualquer, para o formato de data do banco de dados.\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "ConverteMascara",
    insertText: "ConverteMascara(${1:tipoDado}, ${2:valorOrigem}, ${3:alfaDestino}, ${4:mascara});",
    detail: "ConverteMascara(<tipoDado>, <valorOrigem>, <alfaDestino>, <mascara>);",
    documentation: "**ConverteMascara**\n`ConverteMascara(<tipoDado>, <valorOrigem>, <alfaDestino>, <mascara>);`\n\nEsta função converte um valor de entrada (numérico, data, hora ou cadeia de caracteres) para o tipo de dado cadeia de caracteres.\n\n\n_Fonte: cast-de-variavel.md_",
    isSnippet: true,
  },
  {
    label: "ConverteParaMaiusculo",
    insertText: "ConverteParaMaiusculo(${1:texto});",
    detail: "ConverteParaMaiusculo(<texto>);",
    documentation: "**ConverteParaMaiusculo**\n`ConverteParaMaiusculo(<texto>);`\n\nConvertem o conteúdo de uma variável para maiúsculo ou minúsculo.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "ConverteParaMinusculo",
    insertText: "ConverteParaMinusculo(${1:texto});",
    detail: "ConverteParaMinusculo(<texto>)",
    documentation: "**ConverteParaMinusculo**\n`ConverteParaMinusculo(<texto>)`\n\nConvertem o conteúdo de uma variável para maiúsculo ou minúsculo.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "ConverteTexto",
    insertText: "ConverteTexto(${1:codificacao}, ${2:textoOrigem}, ${3:textoDestino});",
    detail: "ConverteTexto(<codificacao>, <textoOrigem>, <textoDestino>);",
    documentation: "**ConverteTexto**\n`ConverteTexto(<codificacao>, <textoOrigem>, <textoDestino>);`\n\nRealiza a substituição de caracteres especiais de acordo com o padrão de codificação informada no primeiro parâmetro, retorna um novo texto com os caracteres convertidos.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "ConverteUnidadeMedida",
    insertText: "ConverteUnidadeMedida(${1:codPro}, ${2:codDer}, ${3:uniMedDe}, ${4:uniMedPara}, ${5:qtde}, ${6:codFor}, ${7:qtdDec}, ${8:codEmp}, ${9:qtdCnv});",
    detail: "Calcula a quantidade convertida de uma unidade de medida (de) para outra unidade de medida (para).",
    documentation: "**ConverteUnidadeMedida**\n`ConverteUnidadeMedida(<codPro>, <codDer>, <uniMedDe>, <uniMedPara>, <qtde>, <codFor>, <qtdDec>, <codEmp>, <qtdCnv>);`\n\nCalcula a quantidade convertida de uma unidade de medida (de) para outra unidade de medida (para).\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "CopiarAlfa",
    insertText: "CopiarAlfa(${1:variavel}, ${2:posicao}, ${3:tamanho});",
    detail: "CopiarAlfa(<variavel>, <posicao>, <tamanho>);",
    documentation: "**CopiarAlfa**\n`CopiarAlfa(<variavel>, <posicao>, <tamanho>);`\n\nCopiam parte do conteúdo de uma variável/campo alfanumérico modificando a própria variável de origem.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "CopiarStr",
    insertText: "CopiarStr(${1:variavel}, ${2:posicao}, ${3:tamanho});",
    detail: "CopiarStr(<variavel>, <posicao>, <tamanho>)",
    documentation: "**CopiarStr**\n`CopiarStr(<variavel>, <posicao>, <tamanho>)`\n\nCopiam parte do conteúdo de uma variável/campo alfanumérico modificando a própria variável de origem.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "CriarArquivoTemporario",
    insertText: "CriarArquivoTemporario(${1:prefixo}, ${2:caminhoArquivo});",
    detail: "CriarArquivoTemporario(<prefixo>, <caminhoArquivo>);",
    documentation: "**CriarArquivoTemporario**\n`CriarArquivoTemporario(<prefixo>, <caminhoArquivo>);`\n\nCria um arquivo temporário com nome único.\n\n\n_Fonte: gerenciamento-avancado-de-arquivos.md_",
    isSnippet: true,
  },
  {
    label: "CriaView",
    insertText: "CriaView(${1:SQL}, ${2:NomeView});",
    detail: "CriaView(Alfa SQL, Alfa End NomeView);",
    documentation: "**CriaView**\n`CriaView(Alfa SQL, Alfa End NomeView);`\n\nCria uma View temporária no banco para otimizar a execução do relatório.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "Cursores",
    insertText: "Cursores();",
    detail: "Cursores();",
    documentation: "**Cursores**\n`Cursores();`\n\nOs cursores são melhores utilizados quando precisa-se de dados atualizados ou que serão lidos apenas uma vez.\n\n\n_Fonte: listas.md_",
  },
  {
    label: "DataExtenso",
    insertText: "DataExtenso(${1:p1}, ${2:extenso});",
    detail: "DataExtenso(<data>, <extenso>);",
    documentation: "**DataExtenso**\n`DataExtenso(<data>, <extenso>);`\n\nEsta função gera o extenso de determinada data.\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "DataHoje",
    insertText: "DataHoje(${1:p1});",
    detail: "DataHoje(<data>);",
    documentation: "**DataHoje**\n`DataHoje(<data>);`\n\nObtém a data atual do sistema operacional (apenas data, sem hora).\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "DataHora",
    insertText: "DataHora(${1:numeroDataHora});",
    detail: "DataHora(<numeroDataHora>);",
    documentation: "**DataHora**\n`DataHora(<numeroDataHora>);`\n\nRetorna um número fracionário onde a parte inteira é a data e a fração são as horas. A parte inteira é a quantidade de dias e a parte fracionada representa as horas do dia.\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "DataHoraUTC",
    insertText: "DataHoraUTC(${1:numeroDataHoraUTC});",
    detail: "DataHoraUTC(<numeroDataHoraUTC>);",
    documentation: "**DataHoraUTC**\n`DataHoraUTC(<numeroDataHoraUTC>);`\n\nRetorna a data em um número fracionário (onde a parte inteira é a data e a fração são as horas) em UTC (Tempo Universal Coordenado).\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "DataInicialFinal",
    insertText: "DataInicialFinal(${1:pDatAtu}, ${2:pTipDat}, ${3:pDatRef}, ${4:pDatIni}, ${5:pDatFim});",
    detail: "DataInicialFinal(Data pDatAtu, Numero pTipDat, Data pDatRef, Data End pDatIni, Data End pDatFim);",
    documentation: "**DataInicialFinal**\n`DataInicialFinal(Data pDatAtu, Numero pTipDat, Data pDatRef, Data End pDatIni, Data End pDatFim);`\n\nRetorna o início e o fim de um período.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "DateToDB",
    insertText: "DateToDB(${1:Date}, ${2:Native}, ${3:DateAlfa});",
    detail: "DateToDB(Numero Date, Numero Native, Alfa End DateAlfa);",
    documentation: "**DateToDB**\n`DateToDB(Numero Date, Numero Native, Alfa End DateAlfa);`\n\nConverte um valor do tipo data para uma variável alfa com uma data compatível com o banco de dados.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "DecimalParaAlfa",
    insertText: "DecimalParaAlfa(${1:p1}, ${2:texto});",
    detail: "DecimalParaAlfa(<numero>, <texto>);",
    documentation: "**DecimalParaAlfa**\n`DecimalParaAlfa(<numero>, <texto>);`\n\nConverte um valor numérico (`Numero`) para alfanumérico preservando a parte decimal na string resultante (formato exibido conforme o ambiente).\n\n\n_Fonte: cast-de-variavel.md_",
    isSnippet: true,
  },
  {
    label: "DecodData",
    insertText: "DecodData(${1:p1}, ${2:dia}, ${3:mes}, ${4:ano});",
    detail: "DecodData(<data>, <dia>, <mes>, <ano>);",
    documentation: "**DecodData**\n\nPermite a separação de uma data em dia, mês e ano para que os dados possam ser usados separadamente.\n\n_Fonte: funcoes-gerais.md_",
    isSnippet: true,
  },
  {
    label: "DeixaNumeros",
    insertText: "DeixaNumeros(${1:texto});",
    detail: "DeixaNumeros(<texto>);",
    documentation: "**DeixaNumeros**\n`DeixaNumeros(<texto>);`\n\nRemove todos os caracteres não numéricos de uma string, mantendo apenas os dígitos.\n\n\n_Fonte: validacao-e-verificacao.md_",
    isSnippet: true,
  },
  {
    label: "DeletarAlfa",
    insertText: "DeletarAlfa(${1:texto}, ${2:posicao}, ${3:quantidade});",
    detail: "DeletarAlfa(<texto>, <posicao>, <quantidade>);",
    documentation: "**DeletarAlfa**\n`DeletarAlfa(<texto>, <posicao>, <quantidade>);`\n\nRemove uma quantidade específica de caracteres de uma posição determinada.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "DeletarStr",
    insertText: "DeletarStr(${1:origem}, ${2:posicao}, ${3:quantidade});",
    detail: "DeletarStr(<origem>, <posicao>, <quantidade>);",
    documentation: "**DeletarStr**\n`DeletarStr(<origem>, <posicao>, <quantidade>);`\n\nElimina parte de um texto.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "DeleteFieldSQL",
    insertText: "DeleteFieldSQL(${1:SectionName}, ${2:TableFieldName});",
    detail: "DeleteFieldSQL(Alfa SectionName, Alfa TableFieldName);",
    documentation: "**DeleteFieldSQL**\n`DeleteFieldSQL(Alfa SectionName, Alfa TableFieldName);`\n\nRetira um campo do SELECT da seção passada como parâmetro.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "DesatLimpezaParamEnt",
    insertText: "DesatLimpezaParamEnt();",
    detail: "nomePorta.DesatLimpezaParamEnt();",
    documentation: "**DesatLimpezaParamEnt**\n`nomePorta.DesatLimpezaParamEnt();`\n\nFunção que desabilita a Limpeza Automática dos Parâmetros de Entrada após a Execução, ou seja, após qualquer execução da porta (função `Executar()`), todos os parâmetros de entrada serão mantidos não sendo necessário alimentá-los novamente para uma nova execução. Caso esta função não seja chamada dentro da Regra LSP, a porta vai assumir a Limpeza Automática como habilitada por padrão.\n\n\n_Fonte: web-service.md_",
  },
  {
    label: "DesCamLista",
    insertText: "DesCamLista(${1:TabelaCampo}, ${2:Item}, ${3:Descricao});",
    detail: "DesCamLista(Alfa TabelaCampo, Alfa Item, Alfa End Descricao);",
    documentation: "**DesCamLista**\n`DesCamLista(Alfa TabelaCampo, Alfa Item, Alfa End Descricao);`\n\nPermite pegar a descrição de um campo lista.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "Desencriptar",
    insertText: "Desencriptar(${1:textoCriptografado}, ${2:textoOriginal});",
    detail: "Desencriptar(<textoCriptografado>, <textoOriginal>);",
    documentation: "**Desencriptar**\n`Desencriptar(<textoCriptografado>, <textoOriginal>);`\n\nDescriptografa uma cadeia de caracteres previamente criptografada.\n\n\n_Fonte: criptografia-e-seguranca.md_",
    isSnippet: true,
  },
  {
    label: "DesfazerTransacao",
    insertText: "DesfazerTransacao();",
    detail: "DesfazerTransacao();",
    documentation: "**DesfazerTransacao**\n`DesfazerTransacao();`\n\nDesfaz a transação no banco de dados executando ROLLBACK.\n\n\n_Fonte: sql.md_",
  },
  {
    label: "DesMontaData",
    insertText: "DesMontaData(${1:p1}, ${2:dia}, ${3:mes}, ${4:ano});",
    detail: "DesMontaData(<data>, <dia>, <mes>, <ano>);",
    documentation: "**DesMontaData**\n`DesMontaData(<data>, <dia>, <mes>, <ano>);`\n\nEsta função desmonta uma data, separando em três variáveis, as informações Dia/Mês/Ano da data.\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "DetPrimConector",
    insertText: "DetPrimConector(${1:Seção}, ${2:Operador});",
    detail: "DetPrimConector(Alfa Seção, Alfa Operador);",
    documentation: "**DetPrimConector**\n`DetPrimConector(Alfa Seção, Alfa Operador);`\n\nPermite determinar qual será o primeiro conector a ser inserido para concatenar na cláusula WHERE.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "Dividir",
    insertText: "Dividir(${1:dividendo}, ${2:divisor}, ${3:resultado});",
    detail: "Dividir(<dividendo>, <divisor>, <resultado>);",
    documentation: "**Dividir**\n`Dividir(<dividendo>, <divisor>, <resultado>);`\n\nRealiza divisão com controle de erro para divisão por zero.\n\n\n_Fonte: operacoes-numericas-avancadas.md_",
    isSnippet: true,
  },
  {
    label: "Encriptar",
    insertText: "Encriptar(${1:textoOriginal}, ${2:textoCriptografado});",
    detail: "Encriptar(<textoOriginal>, <textoCriptografado>);",
    documentation: "**Encriptar**\n`Encriptar(<textoOriginal>, <textoCriptografado>);`\n\nCriptografa uma cadeia de caracteres usando algoritmo interno da Senior.\n\n\n_Fonte: criptografia-e-seguranca.md_",
    isSnippet: true,
  },
  {
    label: "EstaNulo",
    insertText: "EstaNulo(${1:variavel}, ${2:resultado});",
    detail: "EstaNulo(<variavel>, <resultado>);",
    documentation: "**EstaNulo**\n`EstaNulo(<variavel>, <resultado>);`\n\nVerifica se uma variável está nula (vazia ou não inicializada).\n\n\n_Fonte: validacao-e-verificacao.md_",
    isSnippet: true,
  },
  {
    label: "ExcluirArquivoTemporario",
    insertText: "ExcluirArquivoTemporario(${1:caminhoArquivo});",
    detail: "ExcluirArquivoTemporario(<caminhoArquivo>);",
    documentation: "**ExcluirArquivoTemporario**\n`ExcluirArquivoTemporario(<caminhoArquivo>);`\n\nExclui um arquivo temporário criado anteriormente.\n\n\n_Fonte: gerenciamento-avancado-de-arquivos.md_",
    isSnippet: true,
  },
  {
    label: "ExecProg",
    insertText: "ExecProg(${1:comando}, ${2:parametros}, ${3:aguardarTermino});",
    detail: "ExecProg(<comando>, <parametros>, <aguardarTermino>);",
    documentation: "**ExecProg**\n`ExecProg(<comando>, <parametros>, <aguardarTermino>);`\n\nExecuta um programa externo a partir da regra LSP.\n\n\n_Fonte: gerenciamento-avancado-de-arquivos.md_",
    isSnippet: true,
  },
  {
    label: "ExecSQL",
    insertText: "ExecSQL(${1:ComandoSQL});",
    detail: "ExecSQL(<ComandoSQL>);",
    documentation: "**ExecSQL**\n`ExecSQL(<ComandoSQL>);`\n\nExecuta um comando SQL no banco. Pode ser usado para operações INSERT, UPDATE e DELETE.\n\n\n_Fonte: sql.md_",
    isSnippet: true,
  },
  {
    label: "ExecSQLEx",
    insertText: "ExecSQLEx($0);",
    detail: "ExecSQLEx",
    documentation: "**ExecSQLEx**\n\n_Fonte: sql.md_",
    isSnippet: true,
  },
  {
    label: "Executar",
    insertText: "Executar();",
    detail: "nomePorta.Executar();",
    documentation: "**Executar**\n`nomePorta.Executar();`\n\nFunção que executa a requisição da porta, ou seja, realiza as operações para as quais a porta do serviço foi implementada.\n\n\n_Fonte: web-service.md_",
  },
  {
    label: "Extenso",
    insertText: "Extenso(${1:valor}, ${2:tamanhoLinha1}, ${3:tamanhoLinha2}, ${4:tamanhoLinha3}, ${5:linha1}, ${6:linha2}, ${7:linha3});",
    detail: "Extenso(<valor>, <tamanhoLinha1>, <tamanhoLinha2>, <tamanhoLinha3>, <linha1>, <linha2>, <linha3>);",
    documentation: "**Extenso**\n`Extenso(<valor>, <tamanhoLinha1>, <tamanhoLinha2>, <tamanhoLinha3>, <linha1>, <linha2>, <linha3>);`\n\nEsta função gera o extenso de um valor.\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "ExtensoMes",
    insertText: "ExtensoMes(${1:datMon}, ${2:extMes});",
    detail: "ExtensoMes(<datMon>, <extMes>);",
    documentation: "**ExtensoMes**\n`ExtensoMes(<datMon>, <extMes>);`\n\nEsta função monta o extenso do mês de uma determinada data.\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "ExtensoMoeda",
    insertText: "ExtensoMoeda(${1:vlrExt}, ${2:tamLn1}, ${3:tamLn2}, ${4:tamLn3}, ${5:moeIS}, ${6:moeIP}, ${7:moeDS}, ${8:moeDP}, ${9:extLn1}, ${10:extLn2}, ${11:extLn3});",
    detail: "Esta função gera o extenso de um valor com a moeda informada.",
    documentation: "**ExtensoMoeda**\n`ExtensoMoeda(<vlrExt>, <tamLn1>, <tamLn2>, <tamLn3>, <moeIS>, <moeIP>, <moeDS>, <moeDP>, <extLn1>, <extLn2>, <extLn3>);`\n\nEsta função gera o extenso de um valor com a moeda informada.\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "ExtensoSemana",
    insertText: "ExtensoSemana(${1:datMon}, ${2:extSem});",
    detail: "ExtensoSemana(<datMon>, <extSem>);",
    documentation: "**ExtensoSemana**\n`ExtensoSemana(<datMon>, <extSem>);`\n\nEsta função monta o extenso do dia da semana de uma determinada data.\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "FecharCursor",
    insertText: "FecharCursor($0);",
    detail: "FecharCursor",
    documentation: "**FecharCursor**\n\n_Fonte: referencia-rapida.md_",
    isSnippet: true,
  },
  {
    label: "FinalizaBarraProgresso",
    insertText: "FinalizaBarraProgresso();",
    detail: "FinalizaBarraProgresso();",
    documentation: "**FinalizaBarraProgresso**\n`FinalizaBarraProgresso();`\n\nFinaliza e fecha a barra de progresso.\n\n\n_Fonte: interface-e-feedback-do-usuario.md_",
    isSnippet: true,
  },
  {
    label: "FinalizarTransacao",
    insertText: "FinalizarTransacao();",
    detail: "FinalizarTransacao();",
    documentation: "**FinalizarTransacao**\n`FinalizarTransacao();`\n\nFinaliza a transação no banco de dados executando COMMIT.\n\n\n_Fonte: sql.md_",
  },
  {
    label: "Formatar",
    insertText: "Formatar(${1:dado}, ${2:formato});",
    detail: "<variável> = Formatar(<dado>, \"<formato>\");",
    documentation: "**Formatar**\n`<variável> = Formatar(<dado>, \"<formato>\");`\n\nFormata números de acordo com os parâmetros definidos. O formato é o mesmo usado no Borland Delphi 2.0.\n\n\n_Fonte: funcoes-avancadas-de-data-e-dias-uteis.md_",
    isSnippet: true,
  },
  {
    label: "FormatarData",
    insertText: "FormatarData(${1:p1}, ${2:formato}, ${3:dataFormatada});",
    detail: "FormatarData(<data>, <formato>, <dataFormatada>);",
    documentation: "**FormatarData**\n`FormatarData(<data>, <formato>, <dataFormatada>);`\n\nFormata a data em milissegundos gerada pela função DataHora.\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "FormatarN",
    insertText: "FormatarN(${1:dado}, ${2:formato}, ${3:separadordecimal}, ${4:variável});",
    detail: "FormatarN(<dado>, \"<formato>\", \"<separador decimal>\", <variável>);",
    documentation: "**FormatarN**\n`FormatarN(<dado>, \"<formato>\", \"<separador decimal>\", <variável>);`\n\nFormata números com casas decimais de acordo com os parâmetros definidos. O formato é o mesmo usado no Borland Delphi 2.0.\n\n\n_Fonte: funcoes-avancadas-de-data-e-dias-uteis.md_",
    isSnippet: true,
  },
  {
    label: "GeraHash",
    insertText: "GeraHash(${1:texto}, ${2:algoritmo}, ${3:hash});",
    detail: "GeraHash(<texto>, <algoritmo>, <hash>);",
    documentation: "**GeraHash**\n`GeraHash(<texto>, <algoritmo>, <hash>);`\n\nGera um hash criptográfico de um texto usando diferentes algoritmos.\n\n\n_Fonte: criptografia-e-seguranca.md_",
    isSnippet: true,
  },
  {
    label: "GerarNonce",
    insertText: "GerarNonce(${1:nonce});",
    detail: "GerarNonce(<nonce>);",
    documentation: "**GerarNonce**\n`GerarNonce(<nonce>);`\n\nGera um valor Nonce (número aleatório usado uma única vez).\n\n\n_Fonte: criptografia-e-seguranca.md_",
    isSnippet: true,
  },
  {
    label: "GerarPwdDigest",
    insertText: "GerarPwdDigest(${1:nonce}, ${2:created}, ${3:senha}, ${4:digest});",
    detail: "GerarPwdDigest(<nonce>, <created>, <senha>, <digest>);",
    documentation: "**GerarPwdDigest**\n`GerarPwdDigest(<nonce>, <created>, <senha>, <digest>);`\n\nGera o Digest da senha para autenticação WS-Security.\n\n\n_Fonte: criptografia-e-seguranca.md_",
    isSnippet: true,
  },
  {
    label: "GeraSenha",
    insertText: "GeraSenha(${1:tamanho}, ${2:senha});",
    detail: "GeraSenha(<tamanho>, <senha>);",
    documentation: "**GeraSenha**\n`GeraSenha(<tamanho>, <senha>);`\n\nGera uma senha aleatória com caracteres alfanuméricos.\n\n\n_Fonte: criptografia-e-seguranca.md_",
    isSnippet: true,
  },
  {
    label: "GeraToken",
    insertText: "GeraToken(${1:tamanho}, ${2:token});",
    detail: "GeraToken(<tamanho>, <token>);",
    documentation: "**GeraToken**\n`GeraToken(<tamanho>, <token>);`\n\nGera um token criptográfico seguro.\n\n\n_Fonte: criptografia-e-seguranca.md_",
    isSnippet: true,
  },
  {
    label: "HoraParaMinuto",
    insertText: "HoraParaMinuto(${1:hora}, ${2:minuto}, ${3:minutos});",
    detail: "HoraParaMinuto(<hora>, <minuto>, <minutos>);",
    documentation: "**HoraParaMinuto**\n`HoraParaMinuto(<hora>, <minuto>, <minutos>);`\n\nConverte em minutos os valores que representam hora e minuto.\n\n\n_Fonte: operacoes-numericas-avancadas.md_",
    isSnippet: true,
  },
  {
    label: "HttpAlteraCabecalhoRequisicao",
    insertText: "HttpAlteraCabecalhoRequisicao($0);",
    detail: "HttpAlteraCabecalhoRequisicao",
    documentation: "**HttpAlteraCabecalhoRequisicao**\n\n_Fonte: referencia-rapida.md_",
    isSnippet: true,
  },
  {
    label: "HttpDelete",
    insertText: "HttpDelete(${1:Objeto}, ${2:URL}, ${3:HTML});",
    detail: "HttpDelete(Alfa Objeto, Alfa URL, Alfa end HTML);",
    documentation: "**HttpDelete**\n`HttpDelete(Alfa Objeto, Alfa URL, Alfa end HTML);`\n\nExecuta uma requisição HTTP DELETE para remover recursos. Usado para exclusão de dados específicos.\n\n\n_Fonte: http.md_",
    isSnippet: true,
  },
  {
    label: "HttpDeleteBody",
    insertText: "HttpDeleteBody(${1:Objeto}, ${2:URL}, ${3:Dados}, ${4:HTML});",
    detail: "HttpDeleteBody(Alfa Objeto, Alfa URL, Alfa Dados, Alfa end HTML);",
    documentation: "**HttpDeleteBody**\n`HttpDeleteBody(Alfa Objeto, Alfa URL, Alfa Dados, Alfa end HTML);`\n\nExecuta uma requisição HTTP DELETE com dados no corpo da mensagem. Útil para exclusões em lote ou com parâmetros específicos.\n\n\n_Fonte: http.md_",
    isSnippet: true,
  },
  {
    label: "HttpDesabilitaErroResposta",
    insertText: "HttpDesabilitaErroResposta($0);",
    detail: "HttpDesabilitaErroResposta",
    documentation: "**HttpDesabilitaErroResposta**\n\n_Fonte: referencia-rapida.md_",
    isSnippet: true,
  },
  {
    label: "HttpDownload",
    insertText: "HttpDownload(${1:Objeto}, ${2:URL}, ${3:Arquivo});",
    detail: "HttpDownload(Alfa Objeto, Alfa URL, Alfa Arquivo);",
    documentation: "**HttpDownload**\n`HttpDownload(Alfa Objeto, Alfa URL, Alfa Arquivo);`\n\nFaz download de arquivos diretamente para o disco, sem carregar na memória. Ideal para arquivos grandes.\n\n\n_Fonte: http.md_",
    isSnippet: true,
  },
  {
    label: "HttpGet",
    insertText: "HttpGet(${1:Objeto}, ${2:URL}, ${3:HTML});",
    detail: "HttpGet(Alfa Objeto, Alfa URL, Alfa end HTML);",
    documentation: "**HttpGet**\n`HttpGet(Alfa Objeto, Alfa URL, Alfa end HTML);`\n\nExecuta uma requisição HTTP GET para obter dados de um servidor. É o método mais utilizado para consulta de dados em APIs REST.\n\n\n_Fonte: http.md_",
    isSnippet: true,
  },
  {
    label: "HttpLeCodigoResposta",
    insertText: "HttpLeCodigoResposta($0);",
    detail: "HttpLeCodigoResposta",
    documentation: "**HttpLeCodigoResposta**\n\n_Fonte: referencia-rapida.md_",
    isSnippet: true,
  },
  {
    label: "HttpObjeto",
    insertText: "HttpObjeto($0);",
    detail: "HttpObjeto",
    documentation: "**HttpObjeto**\n\n_Fonte: referencia-rapida.md_",
    isSnippet: true,
  },
  {
    label: "HttpPost",
    insertText: "HttpPost(${1:Objeto}, ${2:URL}, ${3:Dados}, ${4:HTML});",
    detail: "HttpPost(Alfa Objeto, Alfa URL, Alfa Dados, Alfa end HTML);",
    documentation: "**HttpPost**\n`HttpPost(Alfa Objeto, Alfa URL, Alfa Dados, Alfa end HTML);`\n\nExecuta uma requisição HTTP POST para enviar dados ao servidor. Utilizado para criação de recursos, envio de formulários e dados em geral.\n\n\n_Fonte: http.md_",
    isSnippet: true,
  },
  {
    label: "HttpPut",
    insertText: "HttpPut(${1:Objeto}, ${2:URL}, ${3:Dados}, ${4:HTML});",
    detail: "HttpPut(Alfa Objeto, Alfa URL, Alfa Dados, Alfa end HTML);",
    documentation: "**HttpPut**\n`HttpPut(Alfa Objeto, Alfa URL, Alfa Dados, Alfa end HTML);`\n\nExecuta uma requisição HTTP PUT para atualizar recursos existentes. Usado para modificar dados de um recurso específico.\n\n\n_Fonte: http.md_",
    isSnippet: true,
  },
  {
    label: "HttpSetaTimeout",
    insertText: "HttpSetaTimeout(${1:Objeto}, ${2:Timeout});",
    detail: "HttpSetaTimeout(Alfa Objeto, Numero Timeout);",
    documentation: "**HttpSetaTimeout**\n`HttpSetaTimeout(Alfa Objeto, Numero Timeout);`\n\nDefine um timeout (tempo limite) para requisições HTTP. Evita travamentos em requisições lentas.\n\n\n_Fonte: http.md_",
    isSnippet: true,
  },
  {
    label: "IniciaBarraProgresso",
    insertText: "IniciaBarraProgresso(${1:titulo}, ${2:mensagemInicial});",
    detail: "IniciaBarraProgresso(<titulo>, <mensagemInicial>);",
    documentation: "**IniciaBarraProgresso**\n`IniciaBarraProgresso(<titulo>, <mensagemInicial>);`\n\nInicia uma barra de progresso para mostrar o andamento de processos longos.\n\n\n_Fonte: interface-e-feedback-do-usuario.md_",
    isSnippet: true,
  },
  {
    label: "IniciarTransacao",
    insertText: "IniciarTransacao();",
    detail: "IniciarTransacao();",
    documentation: "**IniciarTransacao**\n`IniciarTransacao();`\n\nInicia uma transação no banco de dados.\n\n\n_Fonte: sql.md_",
  },
  {
    label: "InsClauSQLCampoDireto",
    insertText: "InsClauSQLCampoDireto(${1:SectionName}, ${2:CampoDireto});",
    detail: "InsClauSQLCampoDireto(Alfa SectionName, Alfa CampoDireto);",
    documentation: "**InsClauSQLCampoDireto**\n`InsClauSQLCampoDireto(Alfa SectionName, Alfa CampoDireto);`\n\nInsere um campo novo no SELECT que poderá ser utilizado para agrupamentos e outros tipos de funções.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "InsClauSQLField",
    insertText: "InsClauSQLField(${1:SeçãoDetalhe}, ${2:Variavel});",
    detail: "InsClauSQLField(\"Seção Detalhe\", Variavel);",
    documentation: "**InsClauSQLField**\n`InsClauSQLField(\"Seção Detalhe\", Variavel);`\n\nInclui um campo de tabela no código SQL montado pelo gerador.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "InsClauSQLFrom",
    insertText: "InsClauSQLFrom(${1:SeçãoDetalhe}, ${2:Variavel});",
    detail: "InsClauSQLFrom(\"Seção Detalhe\", Variavel);",
    documentation: "**InsClauSQLFrom**\n`InsClauSQLFrom(\"Seção Detalhe\", Variavel);`\n\nInclui uma tabela no código SQL montado pelo gerador.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "InsClauSQLGroupBy",
    insertText: "InsClauSQLGroupBy(${1:SectionName}, ${2:GroupByClau});",
    detail: "InsClauSQLGroupBy(Alfa SectionName, Alfa GroupByClau);",
    documentation: "**InsClauSQLGroupBy**\n`InsClauSQLGroupBy(Alfa SectionName, Alfa GroupByClau);`\n\nInsere uma cláusula GROUP BY no SELECT da seção passada como parâmetro.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "InsClauSQLOrderBy",
    insertText: "InsClauSQLOrderBy(${1:SeçãoDetalhe}, ${2:Variavel});",
    detail: "InsClauSQLOrderBy(\"Seção Detalhe\", Variavel);",
    documentation: "**InsClauSQLOrderBy**\n`InsClauSQLOrderBy(\"Seção Detalhe\", Variavel);`\n\nInclui uma cláusula de ordenação no código SQL montado pelo gerador.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "InsClauSQLWhere",
    insertText: "InsClauSQLWhere(${1:SeçãoDetalhe}, ${2:Variavel});",
    detail: "InsClauSQLWhere(\"Seção Detalhe\", Variavel);",
    documentation: "**InsClauSQLWhere**\n`InsClauSQLWhere(\"Seção Detalhe\", Variavel);`\n\nInclui uma cláusula WHERE no código SQL montado pelo gerador.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "InserirAlfa",
    insertText: "InserirAlfa(${1:valor}, ${2:origem}, ${3:posicao});",
    detail: "InserirAlfa(<valor>, <origem>, <posicao>);",
    documentation: "**InserirAlfa**\n`InserirAlfa(<valor>, <origem>, <posicao>);`\n\nInsere um ou mais caracteres em uma variável/campo, a partir da posição indicada.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "InserirStr",
    insertText: "InserirStr(${1:valor}, ${2:origem}, ${3:posicao});",
    detail: "InserirStr(<valor>, <origem>, <posicao>);",
    documentation: "**InserirStr**\n`InserirStr(<valor>, <origem>, <posicao>);`\n\nEsta função insere um ou mais caracteres em uma Variável/Campo, a partir da posição indicada.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "InsEspAlinhDireita",
    insertText: "InsEspAlinhDireita(${1:Valor});",
    detail: "InsEspAlinhDireita(Numero Valor);",
    documentation: "**InsEspAlinhDireita**\n`InsEspAlinhDireita(Numero Valor);`\n\nInsere espaços a direita de todos os controles no modelo.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "InsSQLWhereSimples",
    insertText: "InsSQLWhereSimples(${1:SeçãoDetalhe}, ${2:Variavel});",
    detail: "InsSQLWhereSimples(\"Seção Detalhe\", Variavel);",
    documentation: "**InsSQLWhereSimples**\n`InsSQLWhereSimples(\"Seção Detalhe\", Variavel);`\n\nInsere uma cláusula WHERE dentro de um SQL durante a execução da regra de pré-seleção.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "IntParaAlfa",
    insertText: "IntParaAlfa(${1:inteiro}, ${2:texto});",
    detail: "IntParaAlfa(<inteiro>, <texto>);",
    documentation: "**IntParaAlfa**\n`IntParaAlfa(<inteiro>, <texto>);`\n\nConverte um valor inteiro para o tipo Alfanumérico.\n\n\n_Fonte: cast-de-variavel.md_",
    isSnippet: true,
  },
  {
    label: "IntParaStr",
    insertText: "IntParaStr(${1:inteiro}, ${2:texto});",
    detail: "IntParaStr(<inteiro>, <texto>);",
    documentation: "**IntParaStr**\n`IntParaStr(<inteiro>, <texto>);`\n\nConverte um valor inteiro para o tipo String (Alfanumérico). Esta função é equivalente a `IntParaAlfa` e é mantida para compatibilidade.\n\n\n_Fonte: cast-de-variavel.md_",
    isSnippet: true,
  },
  {
    label: "LerPosicaoAlfa",
    insertText: "LerPosicaoAlfa(${1:origem}, ${2:destino}, ${3:posicao});",
    detail: "LerPosicaoAlfa(<origem>, <destino>, <posicao>);",
    documentation: "**LerPosicaoAlfa**\n`LerPosicaoAlfa(<origem>, <destino>, <posicao>);`\n\nIdentifica qual caracter está em determinada posição do campo/variável de origem.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "LimpaDadosGrade",
    insertText: "LimpaDadosGrade(${1:ControlName});",
    detail: "LimpaDadosGrade(Alfa ControlName);",
    documentation: "**LimpaDadosGrade**\n`LimpaDadosGrade(Alfa ControlName);`\n\nLimpa todos os dados de um controle tipo grade.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "LimpaDadosGrafico",
    insertText: "LimpaDadosGrafico(${1:ControlName});",
    detail: "LimpaDadosGrafico(Alfa ControlName);",
    documentation: "**LimpaDadosGrafico**\n`LimpaDadosGrafico(Alfa ControlName);`\n\nZera e reutiliza um componente do tipo gráfico no mesmo relatório.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "LimpaEspacos",
    insertText: "LimpaEspacos(${1:texto});",
    detail: "LimpaEspacos(<texto>);",
    documentation: "**LimpaEspacos**\n`LimpaEspacos(<texto>);`\n\nLimpa os espaços em branco à direita e à esquerda de uma variável alfanumérica.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "LimpaEspacosDireita",
    insertText: "LimpaEspacosDireita(${1:texto});",
    detail: "LimpaEspacosDireita(<texto>);",
    documentation: "**LimpaEspacosDireita**\n`LimpaEspacosDireita(<texto>);`\n\nLimpa os espaços em branco à direita de uma variável alfanumérica.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "LimpaEspacosEsquerda",
    insertText: "LimpaEspacosEsquerda(${1:texto});",
    detail: "LimpaEspacosEsquerda(<texto>);",
    documentation: "**LimpaEspacosEsquerda**\n`LimpaEspacosEsquerda(<texto>);`\n\nLimpa os espaços em branco à esquerda de uma variável alfanumérica.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "LimpaGerTabAlf",
    insertText: "LimpaGerTabAlf();",
    detail: "LimpaGerTabAlf();",
    documentation: "**LimpaGerTabAlf**\n`LimpaGerTabAlf();`\n\nLimpa o conteúdo do Registro GerTabAlf.\n\n\n_Fonte: funcoes-avancadas-de-data-e-dias-uteis.md_",
    isSnippet: true,
  },
  {
    label: "LimpaGerTabNum",
    insertText: "LimpaGerTabNum();",
    detail: "LimpaGerTabNum();",
    documentation: "**LimpaGerTabNum**\n`LimpaGerTabNum();`\n\nLimpa o conteúdo do Registro GerTabNum.\n\n\n_Fonte: funcoes-avancadas-de-data-e-dias-uteis.md_",
    isSnippet: true,
  },
  {
    label: "LimparParamsEntrada",
    insertText: "LimparParamsEntrada();",
    detail: "nomePorta.LimparParamsEntrada();",
    documentation: "**LimparParamsEntrada**\n`nomePorta.LimparParamsEntrada();`\n\nFunção que realiza a Limpeza dos Parâmetros de Entrada no ato de sua chamada, ou seja, todos os parâmetros de entrada da porta serão limpos ao executar a função.\n\n\n_Fonte: web-service.md_",
  },
  {
    label: "LinhasArquivo",
    insertText: "LinhasArquivo(${1:caminhoArquivo}, ${2:linhas});",
    detail: "LinhasArquivo(<caminhoArquivo>, <linhas>);",
    documentation: "**LinhasArquivo**\n`LinhasArquivo(<caminhoArquivo>, <linhas>);`\n\nConta o número de linhas em um arquivo através de parâmetro de retorno.\n\n\n_Fonte: gerenciamento-avancado-de-arquivos.md_",
    isSnippet: true,
  },
  {
    label: "ListaItem",
    insertText: "ListaItem(${1:texto}, ${2:separador}, ${3:indice}, ${4:item});",
    detail: "ListaItem(<texto>, <separador>, <indice>, <item>);",
    documentation: "**ListaItem**\n`ListaItem(<texto>, <separador>, <indice>, <item>);`\n\nRetorna um item específico de uma lista concatenada.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "ListaQuantidade",
    insertText: "ListaQuantidade(${1:texto}, ${2:separador}, ${3:quantidade});",
    detail: "ListaQuantidade(<texto>, <separador>, <quantidade>);",
    documentation: "**ListaQuantidade**\n`ListaQuantidade(<texto>, <separador>, <quantidade>);`\n\nRetorna a quantidade de itens em uma lista concatenada através de parâmetro de retorno.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "ListaRegraCarregarJson",
    insertText: "ListaRegraCarregarJson(${1:aLista}, ${2:aJson}, ${3:aGrupo}, ${4:aCampos});",
    detail: "ListaRegraCarregarJson(Numero aLista, Alfa aJson, Alfa aGrupo, Alfa aCampos);",
    documentation: "**ListaRegraCarregarJson**\n`ListaRegraCarregarJson(Numero aLista, Alfa aJson, Alfa aGrupo, Alfa aCampos);`\n\nEsta função lê os dados de um arquivo JSON e os carrega em uma lista onde cada campo do JSON é uma coluna na lista e cada registro é uma linha.\n\n\n_Fonte: funcoes-de-lista-de-regras.md_",
    isSnippet: true,
  },
  {
    label: "ListaRegraCriarLista",
    insertText: "ListaRegraCriarLista(${1:numeroLista});",
    detail: "ListaRegraCriarLista(<numeroLista>);",
    documentation: "**ListaRegraCriarLista**\n`ListaRegraCriarLista(<numeroLista>);`\n\nCria uma nova lista de regras para armazenar dados estruturados.\n\n\n_Fonte: funcoes-de-lista-de-regras.md_",
    isSnippet: true,
  },
  {
    label: "ListaRegraObterValorAlfa",
    insertText: "ListaRegraObterValorAlfa(${1:numeroLista}, ${2:nomeCampo}, ${3:valor}, ${4:obteve});",
    detail: "ListaRegraObterValorAlfa(<numeroLista>, <nomeCampo>, <valor>, <obteve>);",
    documentation: "**ListaRegraObterValorAlfa**\n`ListaRegraObterValorAlfa(<numeroLista>, <nomeCampo>, <valor>, <obteve>);`\n\nObtém o valor de um campo específico do registro atual da lista.\n\n\n_Fonte: funcoes-de-lista-de-regras.md_",
    isSnippet: true,
  },
  {
    label: "ListaRegraPrimeiro",
    insertText: "ListaRegraPrimeiro(${1:numeroLista}, ${2:achou});",
    detail: "ListaRegraPrimeiro(<numeroLista>, <achou>);",
    documentation: "**ListaRegraPrimeiro**\n`ListaRegraPrimeiro(<numeroLista>, <achou>);`\n\nPosiciona a lista no primeiro registro.\n\n\n_Fonte: funcoes-de-lista-de-regras.md_",
    isSnippet: true,
  },
  {
    label: "ListaRegraProximo",
    insertText: "ListaRegraProximo(${1:numeroLista}, ${2:achou});",
    detail: "ListaRegraProximo(<numeroLista>, <achou>);",
    documentation: "**ListaRegraProximo**\n`ListaRegraProximo(<numeroLista>, <achou>);`\n\nMove para o próximo registro da lista.\n\n\n_Fonte: funcoes-de-lista-de-regras.md_",
    isSnippet: true,
  },
  {
    label: "ListaSecao",
    insertText: "ListaSecao(${1:Seção});",
    detail: "ListaSecao(Alfa Seção);",
    documentation: "**ListaSecao**\n`ListaSecao(Alfa Seção);`\n\nLista uma seção adicional do modelo a partir de um evento ou regra.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "LSP",
    insertText: "LSP($0);",
    detail: "LSP",
    documentation: "**LSP**\n\n_Fonte: referencia-rapida.md_",
    isSnippet: true,
  },
  {
    label: "Mensagem",
    insertText: "Mensagem($0);",
    detail: "Apresenta a mensagem em tela de acordo com a parametrização do tipo de retorno e da mensagem que ser",
    documentation: "**Mensagem**\n\nApresenta a mensagem em tela de acordo com a parametrização do tipo de retorno e da mensagem que será visualizada.\n\n_Fonte: funcoes-gerais.md_",
    isSnippet: true,
  },
  {
    label: "MontaAbrangencia",
    insertText: "MontaAbrangencia(${1:tabela}, ${2:valores}, ${3:sqlAbr});",
    detail: "MontaAbrangencia(<tabela>, <valores>, <sqlAbr>);",
    documentation: "**MontaAbrangencia**\n`MontaAbrangencia(<tabela>, <valores>, <sqlAbr>);`\n\nFunção utilizada para retornar uma cláusula SQL de acordo com um campo e uma abrangência de valores.\n\n\n_Fonte: validacao-e-verificacao.md_",
    isSnippet: true,
  },
  {
    label: "MontaData",
    insertText: "MontaData(${1:dia}, ${2:mes}, ${3:ano}, ${4:p4});",
    detail: "MontaData(<dia>, <mes>, <ano>, <data>);",
    documentation: "**MontaData**\n`MontaData(<dia>, <mes>, <ano>, <data>);`\n\nEsta função concatena três variáveis, formando uma data. Diferente de `CodData` (que retorna a data), `MontaData` grava o resultado no 4º parâmetro.\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "MontarSQLHisCampo",
    insertText: "MontarSQLHisCampo(${1:NomeTabela}, ${2:CampoTabela}, ${3:SQLMontado});",
    detail: "MontarSQLHisCampo(Alfa NomeTabela, Alfa CampoTabela, Alfa End SQLMontado);",
    documentation: "**MontarSQLHisCampo**\n`MontarSQLHisCampo(Alfa NomeTabela, Alfa CampoTabela, Alfa End SQLMontado);`\n\nMonta o comando SQL para consulta em tabelas de histórico que não possuem sequência.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "MontarSQLHisCampoSeq",
    insertText: "MontarSQLHisCampoSeq(${1:Tabela}, ${2:Campo}, ${3:SQLMontado});",
    detail: "MontarSQLHisCampoSeq(Alfa Tabela, Alfa Campo, Alfa End SQLMontado);",
    documentation: "**MontarSQLHisCampoSeq**\n`MontarSQLHisCampoSeq(Alfa Tabela, Alfa Campo, Alfa End SQLMontado);`\n\nMonta o comando SQL para consulta em tabelas de histórico que possuem sequência.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "MontarSQLHistorico",
    insertText: "MontarSQLHistorico(${1:Tabela}, ${2:p2}, ${3:Xretorno});",
    detail: "MontarSQLHistorico(Alfa Tabela, Data Data, Alfa End Xretorno);",
    documentation: "**MontarSQLHistorico**\n`MontarSQLHistorico(Alfa Tabela, Data Data, Alfa End Xretorno);`\n\nMonta o comando SQL para uso com os históricos do sistema, com base em uma data.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "MontarSQLHistoricoSeq",
    insertText: "MontarSQLHistoricoSeq(${1:Tabela}, ${2:p2}, ${3:Xretorno});",
    detail: "MontarSQLHistoricoSeq(Alfa Tabela, Data Data, Alfa End Xretorno);",
    documentation: "**MontarSQLHistoricoSeq**\n`MontarSQLHistoricoSeq(Alfa Tabela, Data Data, Alfa End Xretorno);`\n\nMonta o comando SQL para uso com os históricos do sistema, com base em uma data e sequência.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "MultiplicaValor",
    insertText: "MultiplicaValor(${1:multiplicando}, ${2:fator}, ${3:retorno});",
    detail: "MultiplicaValor(<multiplicando>, <fator>, <retorno>);",
    documentation: "**MultiplicaValor**\n`MultiplicaValor(<multiplicando>, <fator>, <retorno>);`\n\nEsta função multiplica um número no formato alfanumérico por um fator de multiplicação numérico e retorna o resultado desta multiplicação em uma variável alfanumérica.\n\n\n_Fonte: datas.md_",
    isSnippet: true,
  },
  {
    label: "ObtemIdiomaAtivo",
    insertText: "ObtemIdiomaAtivo(${1:valorIdioma});",
    detail: "ObtemIdiomaAtivo(<valorIdioma>);",
    documentation: "**ObtemIdiomaAtivo**\n`ObtemIdiomaAtivo(<valorIdioma>);`\n\nRetorna o código do idioma utilizado pelo usuário.\n\n\n_Fonte: interface-e-feedback-do-usuario.md_",
    isSnippet: true,
  },
  {
    label: "ObterVersaoSistema",
    insertText: "ObterVersaoSistema(${1:majorVersion}, ${2:minorVersion}, ${3:release}, ${4:build});",
    detail: "ObterVersaoSistema(<majorVersion>, <minorVersion>, <release>, <build>);",
    documentation: "**ObterVersaoSistema**\n`ObterVersaoSistema(<majorVersion>, <minorVersion>, <release>, <build>);`\n\nEsta função retorna a versão do sistema Senior.\n\n\n_Fonte: interface-e-feedback-do-usuario.md_",
    isSnippet: true,
  },
  {
    label: "OcultaBarraProgressoRelatorio",
    insertText: "OcultaBarraProgressoRelatorio(${1:ocultar});",
    detail: "OcultaBarraProgressoRelatorio(<ocultar>);",
    documentation: "**OcultaBarraProgressoRelatorio**\n`OcultaBarraProgressoRelatorio(<ocultar>);`\n\nOculta a barra de progresso padrão durante a execução de relatórios.\n\n\n_Fonte: interface-e-feedback-do-usuario.md_",
    isSnippet: true,
  },
  {
    label: "OrdenacaoSelecionada",
    insertText: "OrdenacaoSelecionada(${1:SelectionName}, ${2:Ordenacao});",
    detail: "OrdenacaoSelecionada(Alfa SelectionName, Alfa End Ordenacao);",
    documentation: "**OrdenacaoSelecionada**\n`OrdenacaoSelecionada(Alfa SelectionName, Alfa End Ordenacao);`\n\nPermite saber qual a ordenação variável selecionada.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "PegarTipoVar",
    insertText: "PegarTipoVar(${1:nomeVariavel}, ${2:tipo});",
    detail: "PegarTipoVar(<nomeVariavel>, <tipo>);",
    documentation: "**PegarTipoVar**\n`PegarTipoVar(<nomeVariavel>, <tipo>);`\n\nRetorna o tipo de uma variável qualquer, passada como string.\n\n\n_Fonte: manipulacao-dinamica-de-variaveis.md_",
    isSnippet: true,
  },
  {
    label: "PegarValorVarAlf",
    insertText: "PegarValorVarAlf(${1:nomeVariavel}, ${2:valorRetorno});",
    detail: "PegarValorVarAlf(<nomeVariavel>, <valorRetorno>);",
    documentation: "**PegarValorVarAlf**\n`PegarValorVarAlf(<nomeVariavel>, <valorRetorno>);`\n\nRetorna o valor de uma variável alfanumérica identificada por nome.\n\n\n_Fonte: manipulacao-dinamica-de-variaveis.md_",
    isSnippet: true,
  },
  {
    label: "PegarValorVarNum",
    insertText: "PegarValorVarNum(${1:nomeVariavel}, ${2:valorRetorno});",
    detail: "PegarValorVarNum(<nomeVariavel>, <valorRetorno>);",
    documentation: "**PegarValorVarNum**\n`PegarValorVarNum(<nomeVariavel>, <valorRetorno>);`\n\nRetorna o valor de uma variável numérica ou de data identificada por nome.\n\n\n_Fonte: manipulacao-dinamica-de-variaveis.md_",
    isSnippet: true,
  },
  {
    label: "PosicaoAlfa",
    insertText: "PosicaoAlfa(${1:subtexto}, ${2:texto}, ${3:posicao});",
    detail: "PosicaoAlfa(<subtexto>, <texto>, <posicao>);",
    documentation: "**PosicaoAlfa**\n`PosicaoAlfa(<subtexto>, <texto>, <posicao>);`\n\nProcuram por uma parte de texto dentro de um campo/variável, retornando a posição inicial através de parâmetro.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "PosicaoStr",
    insertText: "PosicaoStr(${1:subtexto}, ${2:texto}, ${3:posicao});",
    detail: "PosicaoStr(<subtexto>, <texto>, <posicao>)",
    documentation: "**PosicaoStr**\n`PosicaoStr(<subtexto>, <texto>, <posicao>)`\n\nProcuram por uma parte de texto dentro de um campo/variável, retornando a posição inicial através de parâmetro.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "PreenchePagina",
    insertText: "PreenchePagina(${1:Formato}, ${2:FormatoLinha}, ${3:GrossuraLinha}, ${4:CorLinha}, ${5:CorTextura});",
    detail: "Determina que uma página seja preenchida com rasuras.",
    documentation: "**PreenchePagina**\n`PreenchePagina(Numero Formato, Numero FormatoLinha, Numero GrossuraLinha, Alfa CorLinha, Alfa CorTextura);`\n\nDetermina que uma página seja preenchida com rasuras.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "ProcuraEnter",
    insertText: "ProcuraEnter(${1:strProcura}, ${2:strImp}, ${3:strResto});",
    detail: "ProcuraEnter(<strProcura>, <strImp>, <strResto>);",
    documentation: "**ProcuraEnter**\n`ProcuraEnter(<strProcura>, <strImp>, <strResto>);`\n\nEsta função procura um caractere que indica \"enter\" ou nova linha (#13 ou #10) em uma string e retorna a string antes do primeiro enter, e o restante da string original, em variáveis separadas.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "ProximaPagina",
    insertText: "ProximaPagina(${1:Secao}, ${2:Retorno});",
    detail: "ProximaPagina(Alfa Secao, Numero End Retorno);",
    documentation: "**ProximaPagina**\n`ProximaPagina(Alfa Secao, Numero End Retorno);`\n\nPermite verificar se uma determinada seção será impressa na próxima página.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "Proximo",
    insertText: "Proximo($0);",
    detail: "Proximo",
    documentation: "**Proximo**\n\n_Fonte: referencia-rapida.md_",
    isSnippet: true,
  },
  {
    label: "QuebraTexto",
    insertText: "QuebraTexto(${1:texto}, ${2:tamanhoLinha}, ${3:quantidadeLinhas});",
    detail: "QuebraTexto(<texto>, <tamanhoLinha>, <quantidadeLinhas>);",
    documentation: "**QuebraTexto**\n`QuebraTexto(<texto>, <tamanhoLinha>, <quantidadeLinhas>);`\n\nEsta função pega o texto indicado e faz assinalamentos de quebra de linha conforme o Tamanho_Linha especificado, retornando a quantidade de linhas que será usada para imprimir o texto.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "RemoveExpressoesProibidas",
    insertText: "RemoveExpressoesProibidas(${1:textoOriginal}, ${2:textoLimpo});",
    detail: "RemoveExpressoesProibidas(<textoOriginal>, <textoLimpo>);",
    documentation: "**RemoveExpressoesProibidas**\n`RemoveExpressoesProibidas(<textoOriginal>, <textoLimpo>);`\n\nRemove ou valida expressões que podem representar scripts maliciosos.\n\n\n_Fonte: validacao-e-verificacao.md_",
    isSnippet: true,
  },
  {
    label: "RestoDivisao",
    insertText: "RestoDivisao(${1:dividendo}, ${2:divisor}, ${3:resto});",
    detail: "RestoDivisao(<dividendo>, <divisor>, <resto>);",
    documentation: "**RestoDivisao**\n`RestoDivisao(<dividendo>, <divisor>, <resto>);`\n\nCalcula o resto da divisão (operação módulo).\n\n\n_Fonte: operacoes-numericas-avancadas.md_",
    isSnippet: true,
  },
  {
    label: "RetDiaSemana",
    insertText: "RetDiaSemana(${1:pData}, ${2:pDia});",
    detail: "RetDiaSemana(<pData>, <pDia>);",
    documentation: "**RetDiaSemana**\n`RetDiaSemana(<pData>, <pDia>);`\n\nRetorna o dia da semana em forma de número da data de entrada.\n\n\n_Fonte: funcoes-avancadas-de-data-e-dias-uteis.md_",
    isSnippet: true,
  },
  {
    label: "RetDiaUtilAntPos",
    insertText: "RetDiaUtilAntPos(${1:pData}, ${2:pCEP}, ${3:pDataAnt}, ${4:pDataPos});",
    detail: "RetDiaUtilAntPos(<pData>, <pCEP>, <pDataAnt>, <pDataPos>);",
    documentation: "**RetDiaUtilAntPos**\n`RetDiaUtilAntPos(<pData>, <pCEP>, <pDataAnt>, <pDataPos>);`\n\nVerifica se uma data é dia útil ou não, retornando o dia útil imediatamente anterior e o posterior. Se a data informada for dia útil, traz essa data em ambos os retornos.\n\n\n_Fonte: funcoes-avancadas-de-data-e-dias-uteis.md_",
    isSnippet: true,
  },
  {
    label: "RetiraAcentuacao",
    insertText: "RetiraAcentuacao(${1:pString});",
    detail: "RetiraAcentuacao(<pString>);",
    documentation: "**RetiraAcentuacao**\n`RetiraAcentuacao(<pString>);`\n\nRecebe uma string com acentuação e retorna a mesma string sem acentuação e em maiúsculo.\n\n\n_Fonte: funcoes-adicionais-de-manipulacao-de-strings.md_",
    isSnippet: true,
  },
  {
    label: "RetiraCaracteresEspeciais",
    insertText: "RetiraCaracteresEspeciais(${1:Retorno});",
    detail: "RetiraCaracteresEspeciais(<Retorno>);",
    documentation: "**RetiraCaracteresEspeciais**\n`RetiraCaracteresEspeciais(<Retorno>);`\n\nRemove caracteres especiais deixando somente letras e números, removendo todos os outros caracteres.\n\n\n_Fonte: funcoes-adicionais-de-manipulacao-de-strings.md_",
    isSnippet: true,
  },
  {
    label: "RetornaAscII",
    insertText: "RetornaAscII(${1:xNumero}, ${2:xCarAscII});",
    detail: "RetornaAscII(<xNumero>, <xCarAscII>);",
    documentation: "**RetornaAscII**\n`RetornaAscII(<xNumero>, <xCarAscII>);`\n\nRetorna o caracter ASCII correspondente a um número.\n\n\n_Fonte: funcoes-adicionais-de-manipulacao-de-strings.md_",
    isSnippet: true,
  },
  {
    label: "RetornaCampoAlfaTabela",
    insertText: "RetornaCampoAlfaTabela(${1:NomeCampo}, ${2:NomeTabelaView}, ${3:OpcionalWhere}, ${4:pRetorno}, ${5:pAchou});",
    detail: "Busca o conteúdo atual de um campo alfanumérico de uma VIEW temporária.",
    documentation: "**RetornaCampoAlfaTabela**\n`RetornaCampoAlfaTabela(Alfa NomeCampo, Alfa NomeTabelaView, Alfa OpcionalWhere, Alfa End pRetorno, Numero End pAchou);`\n\nBusca o conteúdo atual de um campo alfanumérico de uma VIEW temporária.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "RetornaCampoNumeroTabela",
    insertText: "RetornaCampoNumeroTabela(${1:NomeCampo}, ${2:NomeTabelaView}, ${3:OpcionalWhere}, ${4:pRetorno}, ${5:pAchou});",
    detail: "Busca o conteúdo atual de um campo numérico de uma VIEW temporária.",
    documentation: "**RetornaCampoNumeroTabela**\n`RetornaCampoNumeroTabela(Alfa NomeCampo, Alfa NomeTabelaView, Alfa OpcionalWhere, Numero End pRetorno, Numero End pAchou);`\n\nBusca o conteúdo atual de um campo numérico de uma VIEW temporária.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "RetornarDiasUteisMes",
    insertText: "RetornarDiasUteisMes(${1:aDatabase}, ${2:aTipoRetorno}, ${3:aQtdDiasUteis});",
    detail: "RetornarDiasUteisMes(<aDatabase>, <aTipoRetorno>, <aQtdDiasUteis>);",
    documentation: "**RetornarDiasUteisMes**\n`RetornarDiasUteisMes(<aDatabase>, <aTipoRetorno>, <aQtdDiasUteis>);`\n\nRetorna a quantidade de dias úteis de um mês tomando como base uma determinada data.\n\n\n_Fonte: funcoes-avancadas-de-data-e-dias-uteis.md_",
    isSnippet: true,
  },
  {
    label: "RetornarDiasUteisPeriodo",
    insertText: "RetornarDiasUteisPeriodo(${1:aDataIni}, ${2:aDataFim}, ${3:aQtdDiasUteis});",
    detail: "RetornarDiasUteisPeriodo(<aDataIni>, <aDataFim>, <aQtdDiasUteis>);",
    documentation: "**RetornarDiasUteisPeriodo**\n`RetornarDiasUteisPeriodo(<aDataIni>, <aDataFim>, <aQtdDiasUteis>);`\n\nRetorna a quantidade de dias úteis entre duas datas informadas.\n\n\n_Fonte: funcoes-avancadas-de-data-e-dias-uteis.md_",
    isSnippet: true,
  },
  {
    label: "RetornarQtdDiasAno",
    insertText: "RetornarQtdDiasAno(${1:aData}, ${2:aTipoAno}, ${3:aQtdDiasAno});",
    detail: "RetornarQtdDiasAno(<aData>, <aTipoAno>, <aQtdDiasAno>);",
    documentation: "**RetornarQtdDiasAno**\n`RetornarQtdDiasAno(<aData>, <aTipoAno>, <aQtdDiasAno>);`\n\nRetorna a quantidade de dias do ano tomando como base o ano da data passada, considerando diferentes tipos de ano.\n\n\n_Fonte: funcoes-avancadas-de-data-e-dias-uteis.md_",
    isSnippet: true,
  },
  {
    label: "RetornaValorCFG",
    insertText: "RetornaValorCFG(${1:chave}, ${2:retorno});",
    detail: "RetornaValorCFG(<chave>, <retorno>);",
    documentation: "**RetornaValorCFG**\n`RetornaValorCFG(<chave>, <retorno>);`\n\nResponsável por retornar para a regra o valor de uma determinada chave da Central de Configuração Senior que está sendo utilizada pelo sistema.\n\n\n_Fonte: interface-e-feedback-do-usuario.md_",
    isSnippet: true,
  },
  {
    label: "SaltarPagina",
    insertText: "SaltarPagina();",
    detail: "SaltarPagina();",
    documentation: "**SaltarPagina**\n`SaltarPagina();`\n\nSalta de página manualmente.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
  },
  {
    label: "SelecaoTabelas",
    insertText: "SelecaoTabelas(${1:pSqlSel}, ${2:pCpoRet}, ${3:pTemMas});",
    detail: "SelecaoTabelas(<pSqlSel>, <pCpoRet>, <pTemMas>);",
    documentation: "**SelecaoTabelas**\n`SelecaoTabelas(<pSqlSel>, <pCpoRet>, <pTemMas>);`\n\nTraz os dados de um comando SELECT(SQL) mais elaborado, incluindo funções de agregação como COUNT(), SUM(), etc. Aceita também comandos como GROUP BY, UNION entre outros.\n\n\n_Fonte: sql.md_",
    isSnippet: true,
  },
  {
    label: "SelecionaImpressora",
    insertText: "SelecionaImpressora(${1:pNomeImp});",
    detail: "SelecionaImpressora(Alfa pNomeImp);",
    documentation: "**SelecionaImpressora**\n`SelecionaImpressora(Alfa pNomeImp);`\n\nDefine a impressora padrão para o modelo.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "SetaNumeroTelaEntrada",
    insertText: "SetaNumeroTelaEntrada(${1:NomeCampo}, ${2:Valor});",
    detail: "SetaNumeroTelaEntrada(<NomeCampo>, <Valor>);",
    documentation: "**SetaNumeroTelaEntrada**\n`SetaNumeroTelaEntrada(<NomeCampo>, <Valor>);`\n\nPermite alterar os valores numéricos da tela de entrada do modelo de relatório.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "SetarValorVarAlf",
    insertText: "SetarValorVarAlf(${1:nomeVariavel}, ${2:valor});",
    detail: "SetarValorVarAlf(<nomeVariavel>, <valor>);",
    documentation: "**SetarValorVarAlf**\n`SetarValorVarAlf(<nomeVariavel>, <valor>);`\n\nDefine o valor de uma variável alfanumérica identificada por nome.\n\n\n_Fonte: manipulacao-dinamica-de-variaveis.md_",
    isSnippet: true,
  },
  {
    label: "SetarValorVarNum",
    insertText: "SetarValorVarNum(${1:nomeVariavel}, ${2:valor});",
    detail: "SetarValorVarNum(<nomeVariavel>, <valor>);",
    documentation: "**SetarValorVarNum**\n`SetarValorVarNum(<nomeVariavel>, <valor>);`\n\nDefine o valor de uma variável numérica ou de data identificada por nome.\n\n\n_Fonte: manipulacao-dinamica-de-variaveis.md_",
    isSnippet: true,
  },
  {
    label: "sleep",
    insertText: "sleep(${1:milissegundos});",
    detail: "sleep(<milissegundos>);",
    documentation: "**sleep**\n`sleep(<milissegundos>);`\n\nPausa a execução por um número especificado de milissegundos. Útil para simular tempo de processamento, aguardar operações ou criar delays controlados.\n\n\n_Fonte: interface-e-feedback-do-usuario.md_",
    isSnippet: true,
  },
  {
    label: "SQL_AbrirCursor",
    insertText: "SQL_AbrirCursor($0);",
    detail: "SQL_AbrirCursor",
    documentation: "**SQL_AbrirCursor**\n\n_Fonte: referencia-rapida.md_",
    isSnippet: true,
  },
  {
    label: "SQL_BOF",
    insertText: "SQL_BOF($0);",
    detail: "SQL_BOF",
    documentation: "**SQL_BOF**\n\n_Fonte: cursores.md_",
    isSnippet: true,
  },
  {
    label: "SQL_Criar",
    insertText: "SQL_Criar($0);",
    detail: "SQL_Criar",
    documentation: "**SQL_Criar**\n\n_Fonte: referencia-rapida.md_",
    isSnippet: true,
  },
  {
    label: "SQL_DefinirAlfa",
    insertText: "SQL_DefinirAlfa($0);",
    detail: "SQL_DefinirAlfa",
    documentation: "**SQL_DefinirAlfa**\n\n_Fonte: sql.md_",
    isSnippet: true,
  },
  {
    label: "SQL_DefinirBlob",
    insertText: "SQL_DefinirBlob($0);",
    detail: "SQL_DefinirBlob",
    documentation: "**SQL_DefinirBlob**\n\n_Fonte: sql.md_",
    isSnippet: true,
  },
  {
    label: "SQL_DefinirComando",
    insertText: "SQL_DefinirComando($0);",
    detail: "SQL_DefinirComando",
    documentation: "**SQL_DefinirComando**\n\n_Fonte: referencia-rapida.md_",
    isSnippet: true,
  },
  {
    label: "SQL_DefinirData",
    insertText: "SQL_DefinirData($0);",
    detail: "SQL_DefinirData",
    documentation: "**SQL_DefinirData**\n\n_Fonte: sql.md_",
    isSnippet: true,
  },
  {
    label: "SQL_DefinirInteiro",
    insertText: "SQL_DefinirInteiro($0);",
    detail: "SQL_DefinirInteiro",
    documentation: "**SQL_DefinirInteiro**\n\n_Fonte: sql.md_",
    isSnippet: true,
  },
  {
    label: "SQL_Destruir",
    insertText: "SQL_Destruir($0);",
    detail: "SQL_Destruir",
    documentation: "**SQL_Destruir**\n\n_Fonte: referencia-rapida.md_",
    isSnippet: true,
  },
  {
    label: "SQL_EOF",
    insertText: "SQL_EOF($0);",
    detail: "SQL_EOF",
    documentation: "**SQL_EOF**\n\n_Fonte: referencia-rapida.md_",
    isSnippet: true,
  },
  {
    label: "SQL_FecharCursor",
    insertText: "SQL_FecharCursor($0);",
    detail: "SQL_FecharCursor",
    documentation: "**SQL_FecharCursor**\n\n_Fonte: referencia-rapida.md_",
    isSnippet: true,
  },
  {
    label: "SQL_Proximo",
    insertText: "SQL_Proximo($0);",
    detail: "SQL_Proximo",
    documentation: "**SQL_Proximo**\n\n_Fonte: referencia-rapida.md_",
    isSnippet: true,
  },
  {
    label: "SQL_RetornarAlfa",
    insertText: "SQL_RetornarAlfa($0);",
    detail: "SQL_RetornarAlfa",
    documentation: "**SQL_RetornarAlfa**\n\n_Fonte: referencia-rapida.md_",
    isSnippet: true,
  },
  {
    label: "SQL_RetornarBlob",
    insertText: "SQL_RetornarBlob($0);",
    detail: "SQL_RetornarBlob",
    documentation: "**SQL_RetornarBlob**\n\n_Fonte: cursores.md_",
    isSnippet: true,
  },
  {
    label: "SQL_RetornarBoleano",
    insertText: "SQL_RetornarBoleano($0);",
    detail: "SQL_RetornarBoleano",
    documentation: "**SQL_RetornarBoleano**\n\n_Fonte: cursores.md_",
    isSnippet: true,
  },
  {
    label: "SQL_RetornarData",
    insertText: "SQL_RetornarData($0);",
    detail: "SQL_RetornarData",
    documentation: "**SQL_RetornarData**\n\n_Fonte: cursores.md_",
    isSnippet: true,
  },
  {
    label: "SQL_RetornarFlutuante",
    insertText: "SQL_RetornarFlutuante($0);",
    detail: "SQL_RetornarFlutuante",
    documentation: "**SQL_RetornarFlutuante**\n\n_Fonte: cursores.md_",
    isSnippet: true,
  },
  {
    label: "SQL_RetornarInteiro",
    insertText: "SQL_RetornarInteiro($0);",
    detail: "SQL_RetornarInteiro",
    documentation: "**SQL_RetornarInteiro**\n\n_Fonte: sql.md_",
    isSnippet: true,
  },
  {
    label: "SQL_RetornarSeNulo",
    insertText: "SQL_RetornarSeNulo($0);",
    detail: "SQL_RetornarSeNulo",
    documentation: "**SQL_RetornarSeNulo**\n\n_Fonte: cursores.md_",
    isSnippet: true,
  },
  {
    label: "SQL_UsarAbrangencia",
    insertText: "SQL_UsarAbrangencia($0);",
    detail: "SQL_UsarAbrangencia",
    documentation: "**SQL_UsarAbrangencia**\n\n_Fonte: sql.md_",
    isSnippet: true,
  },
  {
    label: "SQL_UsarSQLSenior2",
    insertText: "SQL_UsarSQLSenior2($0);",
    detail: "SQL_UsarSQLSenior2",
    documentation: "**SQL_UsarSQLSenior2**\n\n_Fonte: sql.md_",
    isSnippet: true,
  },
  {
    label: "StrParaInt",
    insertText: "StrParaInt(${1:texto}, ${2:inteiro});",
    detail: "StrParaInt(<texto>, <inteiro>);",
    documentation: "**StrParaInt**\n`StrParaInt(<texto>, <inteiro>);`\n\nConverte um valor alfanumérico (string) para o tipo Inteiro. Esta função é equivalente a `AlfaParaInt` e é mantida para compatibilidade.\n\n\n_Fonte: cast-de-variavel.md_",
    isSnippet: true,
  },
  {
    label: "SubstAlfa",
    insertText: "SubstAlfa(${1:subtexto}, ${2:novoTexto}, ${3:texto});",
    detail: "SubstAlfa(<subtexto>, <novoTexto>, <texto>);      @ Substitui todas as ocorrências @",
    documentation: "**SubstAlfa**\n`SubstAlfa(<subtexto>, <novoTexto>, <texto>);      @ Substitui todas as ocorrências @`\n\nSubstituem trechos específicos dentro de um texto por outro texto.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "SubstAlfaUmaVez",
    insertText: "SubstAlfaUmaVez(${1:subtexto}, ${2:novoTexto}, ${3:texto});",
    detail: "SubstAlfaUmaVez(<subtexto>, <novoTexto>, <texto>)",
    documentation: "**SubstAlfaUmaVez**\n`SubstAlfaUmaVez(<subtexto>, <novoTexto>, <texto>)`\n\nSubstituem trechos específicos dentro de um texto por outro texto.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "SubstituiFrom",
    insertText: "SubstituiFrom(${1:SectionName}, ${2:NovaClausula}, ${3:TabelaSubstituida});",
    detail: "SubstituiFrom(Alfa SectionName, Alfa NovaClausula, Alfa TabelaSubstituida);",
    documentation: "**SubstituiFrom**\n`SubstituiFrom(Alfa SectionName, Alfa NovaClausula, Alfa TabelaSubstituida);`\n\nSubstitui uma cláusula FROM no SELECT da seção passada como parâmetro.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "TamanhoAlfa",
    insertText: "TamanhoAlfa(${1:origem}, ${2:tamanho});",
    detail: "TamanhoAlfa(<origem>, <tamanho>);",
    documentation: "**TamanhoAlfa**\n`TamanhoAlfa(<origem>, <tamanho>);`\n\nRetornam o tamanho de uma variável/campo alfanumérico através de parâmetro de retorno.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "TamanhoStr",
    insertText: "TamanhoStr(${1:origem}, ${2:tamanho});",
    detail: "TamanhoStr(<origem>, <tamanho>)",
    documentation: "**TamanhoStr**\n`TamanhoStr(<origem>, <tamanho>)`\n\nRetornam o tamanho de uma variável/campo alfanumérico através de parâmetro de retorno.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "TrocaString",
    insertText: "TrocaString(${1:texto}, ${2:textoAntigo}, ${3:textoNovo});",
    detail: "TrocaString(<texto>, <textoAntigo>, <textoNovo>);",
    documentation: "**TrocaString**\n`TrocaString(<texto>, <textoAntigo>, <textoNovo>);`\n\nFunção avançada de substituição com mais opções de controle.\n\n\n_Fonte: strings.md_",
    isSnippet: true,
  },
  {
    label: "TruncaDadosGrade",
    insertText: "TruncaDadosGrade(${1:ControlName}, ${2:Linha}, ${3:Coluna});",
    detail: "TruncaDadosGrade(Alfa ControlName, Numero Linha, Numero Coluna);",
    documentation: "**TruncaDadosGrade**\n`TruncaDadosGrade(Alfa ControlName, Numero Linha, Numero Coluna);`\n\nPermite que o dado de uma determinada célula seja truncado, evitando a quebra de linha.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "Truncar",
    insertText: "Truncar(${1:valor});",
    detail: "vnParteInteira = Truncar(<valor>);",
    documentation: "**Truncar**\n`vnParteInteira = Truncar(<valor>);`\n\nTrunca um número para inteiro, removendo a parte fracionária do número.\n\n\n_Fonte: operacoes-numericas-avancadas.md_",
    isSnippet: true,
  },
  {
    label: "UltimoDia",
    insertText: "UltimoDia(${1:DatAtu});",
    detail: "UltimoDia(<DatAtu>);",
    documentation: "**UltimoDia**\n`UltimoDia(<DatAtu>);`\n\nVerifica qual é o último dia do mês/ano da data informada.\n\n\n_Fonte: funcoes-avancadas-de-data-e-dias-uteis.md_",
    isSnippet: true,
  },
  {
    label: "UltimoRegistro",
    insertText: "UltimoRegistro(${1:SeçãoDetalhe}, ${2:Retorno});",
    detail: "UltimoRegistro(\"Seção Detalhe\", Numero Retorno);",
    documentation: "**UltimoRegistro**\n`UltimoRegistro(\"Seção Detalhe\", Numero Retorno);`\n\nVerifica se o registro que está sendo listado na seção detalhe é o último elemento.\n\n\n_Fonte: funcoes-especificas-do-gerador-de-relatorios.md_",
    isSnippet: true,
  },
  {
    label: "ValorElementoJson",
    insertText: "ValorElementoJson($0);",
    detail: "ValorElementoJson",
    documentation: "**ValorElementoJson**\n\n_Fonte: referencia-rapida.md_",
    isSnippet: true,
  },
  {
    label: "Vantagens",
    insertText: "Vantagens();",
    detail: "Vantagens();",
    documentation: "**Vantagens**\n`Vantagens();`\n\n\n_Fonte: cursores.md_",
  },
  {
    label: "VerificaAbaAtiva",
    insertText: "VerificaAbaAtiva(${1:descricaoAba}, ${2:ativa});",
    detail: "VerificaAbaAtiva(<descricaoAba>, <ativa>);",
    documentation: "**VerificaAbaAtiva**\n`VerificaAbaAtiva(<descricaoAba>, <ativa>);`\n\nVerifica se uma aba específica está ativa na interface.\n\n\n_Fonte: validacao-e-verificacao.md_",
    isSnippet: true,
  },
  {
    label: "VrfAbrA",
    insertText: "VrfAbrA(${1:valor}, ${2:abrangencia}, ${3:resultado});",
    detail: "VrfAbrA(<valor>, <abrangencia>, <resultado>);",
    documentation: "**VrfAbrA**\n`VrfAbrA(<valor>, <abrangencia>, <resultado>);`\n\nVerifica se um valor alfanumérico está dentro de uma abrangência especificada.\n\n\n_Fonte: validacao-e-verificacao.md_",
    isSnippet: true,
  },
  {
    label: "VrfAbrN",
    insertText: "VrfAbrN(${1:valor}, ${2:abrangencia}, ${3:resultado});",
    detail: "VrfAbrN(<valor>, <abrangencia>, <resultado>);",
    documentation: "**VrfAbrN**\n`VrfAbrN(<valor>, <abrangencia>, <resultado>);`\n\nVerifica se um valor numérico está dentro de uma abrangência especificada.\n\n\n_Fonte: validacao-e-verificacao.md_",
    isSnippet: true,
  }
];
export const EXTRACTED_FUNCTION_LABELS: string[] = [
  "AbrirCursor",
  "AdicionaDadosGrade",
  "AlfaParaData",
  "AlfaParaDecimal",
  "AlfaParaInt",
  "AlteraControle",
  "AlteraValorFormula",
  "AnoBissexto",
  "ArqExiste",
  "Arredonda",
  "ArredondaABNT",
  "ArredondarValor",
  "ArredondaValorTipoAcerto",
  "AtivaLimpezaParamEnt",
  "AtualizaBarraProgresso",
  "Base64Decode",
  "Base64Encode",
  "CalculaAlfa",
  "Cancel",
  "CancelarRelatorio",
  "CaracterParaAlfa",
  "CarregaImagemControle",
  "CarregaImgControle",
  "CarregaImgVetorialControle",
  "CarregarTextoArq",
  "CodData",
  "CodigoEspNivel",
  "Concatena",
  "ConfiguraPontoGrafico",
  "ConverteCodificacaoString",
  "ConverteDataBanco",
  "ConverteDataSqlSenior2",
  "ConverteDataToDB",
  "ConverteMascara",
  "ConverteParaMaiusculo",
  "ConverteParaMinusculo",
  "ConverteTexto",
  "ConverteUnidadeMedida",
  "CopiarAlfa",
  "CopiarStr",
  "CriarArquivoTemporario",
  "CriaView",
  "Cursores",
  "DataExtenso",
  "DataHoje",
  "DataHora",
  "DataHoraUTC",
  "DataInicialFinal",
  "DateToDB",
  "DecimalParaAlfa",
  "DecodData",
  "DeixaNumeros",
  "DeletarAlfa",
  "DeletarStr",
  "DeleteFieldSQL",
  "DesatLimpezaParamEnt",
  "DesCamLista",
  "Desencriptar",
  "DesfazerTransacao",
  "DesMontaData",
  "DetPrimConector",
  "Dividir",
  "Encriptar",
  "EstaNulo",
  "ExcluirArquivoTemporario",
  "ExecProg",
  "ExecSQL",
  "ExecSQLEx",
  "Executar",
  "Extenso",
  "ExtensoMes",
  "ExtensoMoeda",
  "ExtensoSemana",
  "FecharCursor",
  "FinalizaBarraProgresso",
  "FinalizarTransacao",
  "Formatar",
  "FormatarData",
  "FormatarN",
  "GeraHash",
  "GerarNonce",
  "GerarPwdDigest",
  "GeraSenha",
  "GeraToken",
  "HoraParaMinuto",
  "HttpAlteraCabecalhoRequisicao",
  "HttpDelete",
  "HttpDeleteBody",
  "HttpDesabilitaErroResposta",
  "HttpDownload",
  "HttpGet",
  "HttpLeCodigoResposta",
  "HttpObjeto",
  "HttpPost",
  "HttpPut",
  "HttpSetaTimeout",
  "IniciaBarraProgresso",
  "IniciarTransacao",
  "InsClauSQLCampoDireto",
  "InsClauSQLField",
  "InsClauSQLFrom",
  "InsClauSQLGroupBy",
  "InsClauSQLOrderBy",
  "InsClauSQLWhere",
  "InserirAlfa",
  "InserirStr",
  "InsEspAlinhDireita",
  "InsSQLWhereSimples",
  "IntParaAlfa",
  "IntParaStr",
  "LerPosicaoAlfa",
  "LimpaDadosGrade",
  "LimpaDadosGrafico",
  "LimpaEspacos",
  "LimpaEspacosDireita",
  "LimpaEspacosEsquerda",
  "LimpaGerTabAlf",
  "LimpaGerTabNum",
  "LimparParamsEntrada",
  "LinhasArquivo",
  "ListaItem",
  "ListaQuantidade",
  "ListaRegraCarregarJson",
  "ListaRegraCriarLista",
  "ListaRegraObterValorAlfa",
  "ListaRegraPrimeiro",
  "ListaRegraProximo",
  "ListaSecao",
  "LSP",
  "Mensagem",
  "MontaAbrangencia",
  "MontaData",
  "MontarSQLHisCampo",
  "MontarSQLHisCampoSeq",
  "MontarSQLHistorico",
  "MontarSQLHistoricoSeq",
  "MultiplicaValor",
  "ObtemIdiomaAtivo",
  "ObterVersaoSistema",
  "OcultaBarraProgressoRelatorio",
  "OrdenacaoSelecionada",
  "PegarTipoVar",
  "PegarValorVarAlf",
  "PegarValorVarNum",
  "PosicaoAlfa",
  "PosicaoStr",
  "PreenchePagina",
  "ProcuraEnter",
  "ProximaPagina",
  "Proximo",
  "QuebraTexto",
  "RemoveExpressoesProibidas",
  "RestoDivisao",
  "RetDiaSemana",
  "RetDiaUtilAntPos",
  "RetiraAcentuacao",
  "RetiraCaracteresEspeciais",
  "RetornaAscII",
  "RetornaCampoAlfaTabela",
  "RetornaCampoNumeroTabela",
  "RetornarDiasUteisMes",
  "RetornarDiasUteisPeriodo",
  "RetornarQtdDiasAno",
  "RetornaValorCFG",
  "SaltarPagina",
  "SelecaoTabelas",
  "SelecionaImpressora",
  "SetaNumeroTelaEntrada",
  "SetarValorVarAlf",
  "SetarValorVarNum",
  "sleep",
  "SQL_AbrirCursor",
  "SQL_BOF",
  "SQL_Criar",
  "SQL_DefinirAlfa",
  "SQL_DefinirBlob",
  "SQL_DefinirComando",
  "SQL_DefinirData",
  "SQL_DefinirInteiro",
  "SQL_Destruir",
  "SQL_EOF",
  "SQL_FecharCursor",
  "SQL_Proximo",
  "SQL_RetornarAlfa",
  "SQL_RetornarBlob",
  "SQL_RetornarBoleano",
  "SQL_RetornarData",
  "SQL_RetornarFlutuante",
  "SQL_RetornarInteiro",
  "SQL_RetornarSeNulo",
  "SQL_UsarAbrangencia",
  "SQL_UsarSQLSenior2",
  "StrParaInt",
  "SubstAlfa",
  "SubstAlfaUmaVez",
  "SubstituiFrom",
  "TamanhoAlfa",
  "TamanhoStr",
  "TrocaString",
  "TruncaDadosGrade",
  "Truncar",
  "UltimoDia",
  "UltimoRegistro",
  "ValorElementoJson",
  "Vantagens",
  "VerificaAbaAtiva",
  "VrfAbrA",
  "VrfAbrN"
];
