/** Lista mínima de palavras reservadas LSP (docs/lsp/palavras-reservadas.md). */
export const RESERVED_WORDS = new Set(
  [
    "definir",
    "alfa",
    "numero",
    "data",
    "lista",
    "cursor",
    "se",
    "senao",
    "enquanto",
    "para",
    "funcao",
    "inicio",
    "fim",
    "fimse",
    "fimenquanto",
    "mensagem",
    "cancel",
    "pare",
    "continue",
    "retorna",
    "erro",
    "advertencia",
    "end",
    "abrir",
    "fechar",
    "ler",
    "gravar",
    "lernl",
    "gravarnl",
    "inserir",
    "regra",
    "vapara",
    "valret",
    "valstr",
    "e",
    "ou",
  ].map((s) => s.toLowerCase())
);

/** Funções que usam parâmetro de saída (não `vn = Func(`). */
export const OUT_PARAM_FUNCS = [
  "TamanhoAlfa",
  "PosicaoAlfa",
  "IntParaAlfa",
  "AlfaParaInt",
  "AlfaParaDecimal",
  "DecimalParaAlfa",
  "AlfaParaData",
  "EstaNulo",
  "ListaQuantidade",
  "CopiarAlfa",
  "Maiuscula",
  "Minuscula",
  "Trim",
  "FormatarData",
  "DataHora",
  "DecodData",
  "MontaData",
  "CaracterParaAlfa",
  "DataHoje",
];

/** Membros/procedimentos de Lista que não são campos (docs/lsp/listas.md). */
export const LIST_BUILTIN_MEMBERS = new Set(
  [
    "definircampos",
    "adicionarcampo",
    "efetivarcampos",
    "adicionar",
    "inserir",
    "editar",
    "gravar",
    "cancelar",
    "excluir",
    "primeiro",
    "ultimo",
    "anterior",
    "proximo",
    "próximo",
    "setarchave",
    "editarchave",
    "vaiparachave",
    "numreg",
    "setanumreg",
    "ida",
    "fda",
    "qtdregistros",
    "limpar",
    "chave",
  ].map((s) => s.toLowerCase())
);

/** Funções de arredondamento válidas (substitutas de `Arredondar`, inexistente). */
export const ROUNDING_FUNCS = [
  {
    name: "Arredonda",
    insert: "Arredonda(${1:vnValor}, ${2:vnCasas});",
    detail: "Arredonda(Numero End Valor, Numero Decimais) — altera o 1º parâmetro",
  },
  {
    name: "ArredondaABNT",
    insert: "ArredondaABNT(${1:vnValor}, ${2:vnCasas});",
    detail: "Mesma forma que Arredonda, regra ABNT",
  },
  {
    name: "ArredondarValor",
    insert: "ArredondarValor(${1:vnValor}, ${2:vnCasas});",
    detail: "ArredondarValor(Valor, Qtde_Casas)",
  },
  {
    name: "ArredondarValorEx",
    insert: "ArredondarValorEx(${1:vnValor}, ${2:vnCasas});",
    detail: "Equivalente a ArredondarValor em vários ambientes",
  },
  {
    name: "ArredondaValorTipoAcerto",
    insert: "ArredondaValorTipoAcerto(${1:vnValor}, ${2:vnTipoAcerto});",
    detail: "ArredondaValorTipoAcerto(valor, tipo) — sem espaços no nome",
  },
] as const;

/** Funções de truncamento válidas. */
export const TRUNCATE_FUNCS = [
  {
    name: "Truncar",
    insert: "${1:vnResultado} = Truncar(${2:vnValor});",
    detail: "Truncar(Numero vnValor) — retorna inteiro truncado (usar atribuição)",
  },
  {
    name: "TruncarDecimal",
    insert: "TruncarDecimal(${1:vnValor}, ${2:vnDecimais});",
    detail: "TruncarDecimal(Numero End Valor, Numero pDecimais) — altera o 1º parâmetro",
  },
  {
    name: "TruncarValor",
    insert: "TruncarValor(${1:vnValor});",
    detail: "TruncarValor(Numero End ValorVariavel) — trunca na própria variável",
  },
] as const;

export const IMPLEMENTED_RULE_IDS = [
  "SYN001",
  "SYN002",
  "SYN003",
  "SYN004",
  "SYN005",
  "SYN006",
  "SYN007",
  "SYN008",
  "SYN009",
  "SYN010",
  "RUL001",
  "RUL002",
  "RUL003",
  "RUL004",
  "RUL005",
  "RUL006",
  "RUL007",
  "RUL008",
  "RUL009",
  "RUL010",
  "RUL011",
  "RUL012",
  "RUL013",
  "RUL014",
  "RUL015",
  "RUL016",
  "RUL017",
  "RUL018",
  "RUL019",
  "FUN001",
  "FUN002",
  "FUN003",
  "FUN004",
  "FUN005",
  "FUN006",
  "FUN007",
  "FUN008",
  "FUN009",
  "SEM001",
  "SEM002",
  "SEM003",
  "SEM004",
  "SQL001",
  "SQL002",
  "SQL003",
  "SQL004",
  "SQL005",
  "SQL006",
  "SQL007",
  "SQL008",
  "SQL009",
] as const;
